apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: klearn
  labels:
    name: my-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 5000
